language: python
os:
  - linux
python:
  - "3.6"
script:
  - pytest --cov=noisereduce/
after_success:
  - coveralls
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt